// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rbgdwlcwupmysdnpkwct.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJiZ2R3bGN3dXBteXNkbnBrd2N0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwODEyNjAsImV4cCI6MjA2MzY1NzI2MH0.AZDLg4NaMnt0lLKy64XRAeoVHUzIsClwwjgD27eVCCE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);